---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: ubuntu-12.04
  driver:
      image: ubuntu:12.04

suites:
  - name: default
    run_list:
      - recipe[export-node-tests::default]
      - recipe[export-node::default]
