name             'export-node'
maintainer       'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license          'Apache 2.0'
description      'Exports node attributes to a json file'
version          '1.0.1'
issues_url       'https://github.com/mwrock/export-node/issues'
source_url       'https://github.com/mwrock/export-node'
