name             'export-node-tests'
maintainer       'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license          'Apache 2.0'
description      'tests the export-node cookbook'
version          '0.1.0'
issues_url       'https://github.com/mwrock/export-node/issues'
source_url       'https://github.com/mwrock/export-node'
